### Base URL
@baseUrl = http://localhost:8080
@contentType = application/json

### STEP 1: Health Check
GET {{baseUrl}}/api/v1/health

### STEP 2: Register User
POST {{baseUrl}}/api/v1/register
Content-Type: {{contentType}}

{
  "username": "testuser",
  "name": "Test User",
  "email": "testuser@example.com",
  "password": "password123"
}

### STEP 3: Login dan copy token secara manual
POST {{baseUrl}}/api/v1/login
Content-Type: {{contentType}}

{
  "email": "testuser@example.com",
  "password": "password123"
}

### STEP 4: Set token manually (copy dari response login di atas)
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTcxOTg4NjAsInR5cGUiOiJhY2Nlc3MiLCJ1c2VyX2lkIjoiMTI3NTdkMTEtMzg1ZC00OTY3LTkzY2MtYTgzOWRhZGU0YmQ1In0.Mz7zyCeduHkAwIxRYWZXihKscbIqXgYQpiTnbRNixt0
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3NzU5NTEsInR5cGUiOiJyZWZyZXNoIiwidXNlcl9pZCI6IjEyNzU3ZDExLTM4NWQtNDk2Ny05M2NjLWE4MzlkYWRlNGJkNSJ9.eJTcHtv5e_yTusNVbZkbkOfLxCuI0P3yqMJzdqIGVLc

### STEP 5: Get Profile dengan token
GET {{baseUrl}}/api/v1/profile
Authorization: Bearer {{authToken}}

### STEP 6: Refresh Token
POST {{baseUrl}}/api/v1/refresh
Content-Type: application/json
Accept: application/json

{
  "refresh_token": "{{refreshToken}}"
}

### STEP 6: Get All Users
GET {{baseUrl}}/api/v1/users
Authorization: Bearer {{authToken}}

### STEP 7: Get User By Id
GET {{baseUrl}}/api/v1/users/925f58fb-1ece-4962-af6c-a190e809257f
Authorization: Bearer {{authToken}}

### STEP 8: Put User By Id
PUT {{baseUrl}}/api/v1/users/925f58fb-1ece-4962-af6c-a190e809257f
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "name": "Admin Update",
    "email": "admin.update@example.com"
}

### STEP 8: Post New Password
POST {{baseUrl}}/api/v1/users/12757d11-385d-4967-93cc-a839dade4bd5/change-password
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "current_password": "password",
    "new_password": "password123"
}

### STEP 7: Get Health (public)
GET {{baseUrl}}/api/v1/health

### STEP 8: Test invalid token
GET {{baseUrl}}/api/v1/users
Authorization: Bearer invalid_token_here

### STEP 9: Test without token
GET {{baseUrl}}/api/v1/users

### STEP 8: Post Logout
POST {{baseUrl}}/api/v1/logout
Authorization: Bearer {{authToken}}
