# File ini berisi definisi parameter yang bisa di-reuse
parameters:
  UserId:
    name: id
    in: path
    required: true
    schema: { type: string, format: uuid }
    description: "ID Pengguna (UUID)"
  RoleId:
    name: id
    in: path
    required: true
    schema: { type: string, format: uuid }
    description: "ID Role (UUID)"
  PermissionId:
    name: id
    in: path
    required: true
    schema: { type: string, format: uuid }
    description: "ID Permission (UUID)"
  StudentId:
    name: id
    in: path
    required: true
    schema: { type: string, format: uuid }
    description: "ID Siswa (UUID)"
  ParentId:
    name: id
    in: path
    required: true
    schema: { type: string, format: uuid }
    description: "ID Orang Tua (UUID)"
  GuardianId:
    name: id
    in: path
    required: true
    schema: { type: string, format: uuid }
    description: "ID Wali (UUID)"
